force-app/main/default/objects/Telemetry__c/Telemetry__c.object-meta.xml
<CustomObject>
    <label>Telemetry</label>
    <nameField>
        <label>Telemetry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Telemetrys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Telemetry__c/fields/Failure_Probability__c.field-meta.xml
<CustomField>
    <fullName>Failure_Probability__c</fullName>
    <label>Failure Probability</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Telemetry__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <label>Temperature</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Telemetry__c/fields/Vibration__c.field-meta.xml
<CustomField>
    <fullName>Vibration__c</fullName>
    <label>Vibration</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Telemetry__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Telemetrys</relationshipLabel>
    <relationshipName>Telemetrys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TelemetryController.cls
public with sharing class TelemetryController {

    @AuraEnabled(cacheable=true)
    public static List<Telemetry__c> getTelemetry(Id serviceAppointmentId){

        ServiceAppointment sa = [
            SELECT ParentRecordId
            FROM ServiceAppointment
            WHERE Id = :serviceAppointmentId
            LIMIT 1
        ];

        if(sa.ParentRecordId == null){
            return new List<Telemetry__c>();
        }

        return [
            SELECT Id,
                   Temperature__c,
                   Vibration__c,
                   Failure_Probability__c,
                   Timestamp__c
            FROM Telemetry__c
            WHERE Work_Order__c = :sa.ParentRecordId
            ORDER BY Timestamp__c DESC
            LIMIT 20
        ];
    }


    @AuraEnabled(cacheable=true)
    public static WorkOrder getWorkOrder(Id serviceAppointmentId){

        ServiceAppointment sa = [
            SELECT ParentRecordId
            FROM ServiceAppointment
            WHERE Id = :serviceAppointmentId
            LIMIT 1
        ];

        if(sa.ParentRecordId == null){
            return null;
        }

        return [
            SELECT Id,
                   Asset.Name,
                   Asset.SerialNumber
            FROM WorkOrder
            WHERE Id = :sa.ParentRecordId
            LIMIT 1
        ];
    }
}